/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MENU;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
/**
 *
 * @author alexi
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barra_superior = new javax.swing.JPanel();
        BUTTON_INICIO = new javax.swing.JToggleButton();
        BUTTON_CUENTAS = new javax.swing.JToggleButton();
        BUTTON_INGRESOS = new javax.swing.JToggleButton();
        BUTTON_PRESUPUESTOS = new javax.swing.JToggleButton();
        BUTTON_GASTOS = new javax.swing.JToggleButton();
        BUTTON_AYUDA = new javax.swing.JToggleButton();
        BUTTON_CERRAR_SESION = new javax.swing.JButton();
        INTERFAZ_INTERACTIVA_PANE = new javax.swing.JTabbedPane();
        INICIO_TAB_SCROLLPANE = new javax.swing.JScrollPane();
        INICIO_PANEL = new javax.swing.JPanel();
        SALDO_ACTUAL_PANEL = new javax.swing.JPanel();
        balanceLabel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        RESPONSABILIDAD_PANEL = new javax.swing.JPanel();
        liabilitiesLabel = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        INGRESOS_DEL_MES_PANEL = new javax.swing.JPanel();
        incomeLabel = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        GASTOS_DEL_MES_PANEL = new javax.swing.JPanel();
        expenseLabel = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        GENERAR_GRAFICO_BUTTON = new javax.swing.JButton();
        TRANSACCIONES_TEXT = new javax.swing.JLabel();
        TABLA_DE_TRANSACCIONES = new javax.swing.JScrollPane();
        transactionTable = new javax.swing.JTable();
        VISUALIZACION_AHORRO = new javax.swing.JPanel();
        AHORRO_MENSUAL_TXT = new javax.swing.JLabel();
        BARRA_DE_PROGRESO = new javax.swing.JProgressBar();
        MONTO_AHORRADO = new javax.swing.JLabel();
        CUENTAS_TAB = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        accountTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        deleteAccount = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        createAccount = new javax.swing.JButton();
        INGRESOS_TAB_SCROLLPANE = new javax.swing.JScrollPane();
        Income_tab = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        incomeSourceComboBox = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        incomeAmount = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        incomeAccountName = new javax.swing.JComboBox<>();
        addIncomeButton = new javax.swing.JButton();
        resetIncomeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        addIncomeSource = new javax.swing.JButton();
        incomeSourceTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        incomeTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        PRESUPUESTOS_TAB_SCROLLPANE = new javax.swing.JScrollPane();
        Budget_tab = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jLabel33 = new javax.swing.JLabel();
        BudgetExpenseCategoryComboBox = new javax.swing.JComboBox<>();
        removeBudgetComboBox = new javax.swing.JComboBox<>();
        BudgetAmount = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        BudgetExpenseCategoryTextField = new javax.swing.JTextField();
        addBudgetExpenseCategoryButton = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        removeBudgetButton = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        addBudget = new javax.swing.JButton();
        targetAmountTextField = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        addTargetAmountButton = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        budgetTable = new javax.swing.JTable();
        GASTOS_TAB_SCROLLPANE = new javax.swing.JScrollPane();
        Expense = new javax.swing.JPanel();
        Expense_Tab = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jLabel15 = new javax.swing.JLabel();
        expenseAccountName = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        expenseCategoryComboBox = new javax.swing.JComboBox<>();
        expenseCategoryTextField = new javax.swing.JTextField();
        expenseRemark = new javax.swing.JTextField();
        ExpenseAddButton = new javax.swing.JButton();
        ExpenseResetButton = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        expenseTable = new javax.swing.JTable();
        addExpenseCategory = new javax.swing.JButton();
        expenseAmount = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1530, 900));

        barra_superior.setBackground(new java.awt.Color(204, 0, 0));
        barra_superior.setMaximumSize(new java.awt.Dimension(1510, 139));
        barra_superior.setMinimumSize(new java.awt.Dimension(1510, 139));
        barra_superior.setPreferredSize(new java.awt.Dimension(1510, 139));

        BUTTON_INICIO.setBackground(new java.awt.Color(204, 0, 0));
        BUTTON_INICIO.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        BUTTON_INICIO.setForeground(new java.awt.Color(255, 255, 255));
        BUTTON_INICIO.setText("INICIO");

        BUTTON_CUENTAS.setBackground(new java.awt.Color(204, 0, 0));
        BUTTON_CUENTAS.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        BUTTON_CUENTAS.setForeground(new java.awt.Color(255, 255, 255));
        BUTTON_CUENTAS.setText("CUENTAS");
        BUTTON_CUENTAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_CUENTASActionPerformed(evt);
            }
        });

        BUTTON_INGRESOS.setBackground(new java.awt.Color(204, 0, 0));
        BUTTON_INGRESOS.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        BUTTON_INGRESOS.setForeground(new java.awt.Color(255, 255, 255));
        BUTTON_INGRESOS.setText("INGRESOS");

        BUTTON_PRESUPUESTOS.setBackground(new java.awt.Color(204, 0, 0));
        BUTTON_PRESUPUESTOS.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        BUTTON_PRESUPUESTOS.setForeground(new java.awt.Color(255, 255, 255));
        BUTTON_PRESUPUESTOS.setText("PRESUPUESTO");

        BUTTON_GASTOS.setBackground(new java.awt.Color(204, 0, 0));
        BUTTON_GASTOS.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        BUTTON_GASTOS.setForeground(new java.awt.Color(255, 255, 255));
        BUTTON_GASTOS.setText("GASTOS");

        BUTTON_AYUDA.setBackground(new java.awt.Color(204, 0, 0));
        BUTTON_AYUDA.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        BUTTON_AYUDA.setForeground(new java.awt.Color(255, 255, 255));
        BUTTON_AYUDA.setText("AYUDA");

        BUTTON_CERRAR_SESION.setBackground(new java.awt.Color(0, 0, 0));
        BUTTON_CERRAR_SESION.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        BUTTON_CERRAR_SESION.setForeground(new java.awt.Color(255, 255, 255));
        BUTTON_CERRAR_SESION.setText("CERRAR SESIÓN");
        BUTTON_CERRAR_SESION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_CERRAR_SESIONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout barra_superiorLayout = new javax.swing.GroupLayout(barra_superior);
        barra_superior.setLayout(barra_superiorLayout);
        barra_superiorLayout.setHorizontalGroup(
            barra_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barra_superiorLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(BUTTON_INICIO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(BUTTON_CUENTAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(BUTTON_INGRESOS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(BUTTON_PRESUPUESTOS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(BUTTON_GASTOS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(BUTTON_AYUDA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addComponent(BUTTON_CERRAR_SESION, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        barra_superiorLayout.setVerticalGroup(
            barra_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barra_superiorLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(BUTTON_INICIO, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(barra_superiorLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(BUTTON_CUENTAS, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(barra_superiorLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(BUTTON_INGRESOS, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(barra_superiorLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(BUTTON_PRESUPUESTOS, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(barra_superiorLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(BUTTON_GASTOS, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(barra_superiorLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(BUTTON_AYUDA, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(barra_superiorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(BUTTON_CERRAR_SESION, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        INTERFAZ_INTERACTIVA_PANE.setBackground(new java.awt.Color(255, 255, 255));

        INICIO_TAB_SCROLLPANE.setBackground(new java.awt.Color(255, 255, 255));

        INICIO_PANEL.setBackground(new java.awt.Color(255, 255, 255));

        SALDO_ACTUAL_PANEL.setBackground(new java.awt.Color(204, 204, 204));
        SALDO_ACTUAL_PANEL.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        SALDO_ACTUAL_PANEL.setLayout(null);

        balanceLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        balanceLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceLabelActionPerformed(evt);
            }
        });
        SALDO_ACTUAL_PANEL.add(balanceLabel);
        balanceLabel.setBounds(50, 130, 130, 30);

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel9.setText("SALDO ACTUAL ");
        SALDO_ACTUAL_PANEL.add(jLabel9);
        jLabel9.setBounds(50, 80, 170, 40);

        RESPONSABILIDAD_PANEL.setBackground(new java.awt.Color(204, 204, 204));
        RESPONSABILIDAD_PANEL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        liabilitiesLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RESPONSABILIDAD_PANEL.add(liabilitiesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 140, 30));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel10.setText("RESPONSABILIDAD");
        RESPONSABILIDAD_PANEL.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        INGRESOS_DEL_MES_PANEL.setBackground(new java.awt.Color(204, 204, 204));
        INGRESOS_DEL_MES_PANEL.setLayout(null);

        incomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        INGRESOS_DEL_MES_PANEL.add(incomeLabel);
        incomeLabel.setBounds(50, 130, 130, 30);

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel11.setText("INGRESOS DEL MES ");
        INGRESOS_DEL_MES_PANEL.add(jLabel11);
        jLabel11.setBounds(30, 80, 220, 40);

        GASTOS_DEL_MES_PANEL.setBackground(new java.awt.Color(204, 204, 204));
        GASTOS_DEL_MES_PANEL.setLayout(null);

        expenseLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GASTOS_DEL_MES_PANEL.add(expenseLabel);
        expenseLabel.setBounds(50, 130, 130, 30);

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel12.setText("GASTOS DEL MES ");
        GASTOS_DEL_MES_PANEL.add(jLabel12);
        jLabel12.setBounds(30, 80, 190, 40);
        GASTOS_DEL_MES_PANEL.add(jLabel4);
        jLabel4.setBounds(60, 20, 70, 50);

        GENERAR_GRAFICO_BUTTON.setBackground(new java.awt.Color(0, 0, 0));
        GENERAR_GRAFICO_BUTTON.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        GENERAR_GRAFICO_BUTTON.setForeground(new java.awt.Color(255, 255, 255));
        GENERAR_GRAFICO_BUTTON.setText("Generar Gráfico");
        GENERAR_GRAFICO_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GENERAR_GRAFICO_BUTTONActionPerformed(evt);
            }
        });

        TRANSACCIONES_TEXT.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        TRANSACCIONES_TEXT.setText("Transacciones");

        transactionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "N° de Transacción", "Tipo de Cuenta", "Tipo de Transacción", "Monto ", "Fecha y Hora", "Datos"
            }
        ));
        TABLA_DE_TRANSACCIONES.setViewportView(transactionTable);

        VISUALIZACION_AHORRO.setBackground(new java.awt.Color(214, 214, 214));
        VISUALIZACION_AHORRO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AHORRO_MENSUAL_TXT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AHORRO_MENSUAL_TXT.setText("Ahorro Mensual");
        VISUALIZACION_AHORRO.add(AHORRO_MENSUAL_TXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 40));

        BARRA_DE_PROGRESO.setBackground(new java.awt.Color(255, 255, 255));
        BARRA_DE_PROGRESO.setForeground(new java.awt.Color(33, 225, 65));
        VISUALIZACION_AHORRO.add(BARRA_DE_PROGRESO, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 240, 40));

        MONTO_AHORRADO.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MONTO_AHORRADO.setText("No Data Available");
        VISUALIZACION_AHORRO.add(MONTO_AHORRADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 130, -1));

        javax.swing.GroupLayout INICIO_PANELLayout = new javax.swing.GroupLayout(INICIO_PANEL);
        INICIO_PANEL.setLayout(INICIO_PANELLayout);
        INICIO_PANELLayout.setHorizontalGroup(
            INICIO_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(INICIO_PANELLayout.createSequentialGroup()
                .addGroup(INICIO_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(INICIO_PANELLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(SALDO_ACTUAL_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(RESPONSABILIDAD_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(INGRESOS_DEL_MES_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(GASTOS_DEL_MES_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(INICIO_PANELLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(INICIO_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(INICIO_PANELLayout.createSequentialGroup()
                                .addComponent(GENERAR_GRAFICO_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addComponent(VISUALIZACION_AHORRO, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TRANSACCIONES_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TABLA_DE_TRANSACCIONES, javax.swing.GroupLayout.PREFERRED_SIZE, 1416, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        INICIO_PANELLayout.setVerticalGroup(
            INICIO_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(INICIO_PANELLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(INICIO_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GASTOS_DEL_MES_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SALDO_ACTUAL_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RESPONSABILIDAD_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(INGRESOS_DEL_MES_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TRANSACCIONES_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TABLA_DE_TRANSACCIONES, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(INICIO_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(VISUALIZACION_AHORRO, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(GENERAR_GRAFICO_BUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        INICIO_TAB_SCROLLPANE.setViewportView(INICIO_PANEL);

        INTERFAZ_INTERACTIVA_PANE.addTab("INICIO", INICIO_TAB_SCROLLPANE);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Delete Account");

        accountTable.setAutoCreateRowSorter(true);
        accountTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        accountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Account Name", "Current Balance", "Total Expenses"
            }
        ));
        accountTable.setGridColor(new java.awt.Color(204, 204, 204));
        accountTable.setRowHeight(24);
        accountTable.setRowSelectionAllowed(false);
        accountTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        accountTable.setShowGrid(true);
        accountTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(accountTable);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Accounts");

        deleteAccount.setBackground(new java.awt.Color(55, 98, 217));
        deleteAccount.setForeground(new java.awt.Color(255, 255, 255));
        deleteAccount.setText("Delete");
        deleteAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccountActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Create Account");

        jLabel8.setText("Name");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        createAccount.setBackground(new java.awt.Color(55, 98, 217));
        createAccount.setForeground(new java.awt.Color(255, 255, 255));
        createAccount.setText("Create");
        createAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CUENTAS_TABLayout = new javax.swing.GroupLayout(CUENTAS_TAB);
        CUENTAS_TAB.setLayout(CUENTAS_TABLayout);
        CUENTAS_TABLayout.setHorizontalGroup(
            CUENTAS_TABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CUENTAS_TABLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(CUENTAS_TABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CUENTAS_TABLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(368, 368, 368)
                        .addComponent(jLabel5))
                    .addGroup(CUENTAS_TABLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(48, 48, 48)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(createAccount)
                        .addGap(168, 168, 168)
                        .addComponent(jLabel2)
                        .addGap(48, 48, 48)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(deleteAccount))
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        CUENTAS_TABLayout.setVerticalGroup(
            CUENTAS_TABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CUENTAS_TABLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(CUENTAS_TABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(CUENTAS_TABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        INTERFAZ_INTERACTIVA_PANE.addTab("CUENTAS", CUENTAS_TAB);

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel21.setText("INGRESOS");
        jPanel12.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 50));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Date");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Source");

        incomeSourceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--" }));
        incomeSourceComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomeSourceComboBoxActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("Account");

        incomeAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomeAmountActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("Amount");

        incomeAccountName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--" }));
        incomeAccountName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomeAccountNameActionPerformed(evt);
            }
        });

        addIncomeButton.setBackground(new java.awt.Color(55, 98, 217));
        addIncomeButton.setForeground(new java.awt.Color(255, 255, 255));
        addIncomeButton.setText("Add");
        addIncomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIncomeButtonActionPerformed(evt);
            }
        });

        resetIncomeButton.setBackground(new java.awt.Color(55, 98, 217));
        resetIncomeButton.setForeground(new java.awt.Color(255, 255, 255));
        resetIncomeButton.setText("Reset");
        resetIncomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetIncomeButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("New Source");

        addIncomeSource.setBackground(new java.awt.Color(55, 98, 217));
        addIncomeSource.setForeground(new java.awt.Color(255, 255, 255));
        addIncomeSource.setText("Add");
        addIncomeSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIncomeSourceActionPerformed(evt);
            }
        });

        incomeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Account", "Date", "Source", "Amount"
            }
        ));
        jScrollPane2.setViewportView(incomeTable);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Incomes");

        javax.swing.GroupLayout Income_tabLayout = new javax.swing.GroupLayout(Income_tab);
        Income_tab.setLayout(Income_tabLayout);
        Income_tabLayout.setHorizontalGroup(
            Income_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Income_tabLayout.createSequentialGroup()
                .addGroup(Income_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Income_tabLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Income_tabLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel25)
                        .addGap(90, 90, 90)
                        .addComponent(incomeAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Income_tabLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel24)
                        .addGap(99, 99, 99)
                        .addComponent(incomeSourceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(incomeSourceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(addIncomeSource, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Income_tabLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel26)
                        .addGap(90, 90, 90)
                        .addComponent(incomeAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Income_tabLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(addIncomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(resetIncomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Income_tabLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3))
                    .addGroup(Income_tabLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(578, 578, 578))
        );
        Income_tabLayout.setVerticalGroup(
            Income_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Income_tabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(Income_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(incomeAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(Income_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(incomeSourceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(incomeSourceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addIncomeSource, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(Income_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(incomeAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(Income_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addIncomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetIncomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        INGRESOS_TAB_SCROLLPANE.setViewportView(Income_tab);

        INTERFAZ_INTERACTIVA_PANE.addTab("INGRESOS", INGRESOS_TAB_SCROLLPANE);

        jPanel14.setBackground(new java.awt.Color(204, 204, 204));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel32.setText("AÑADIR PRESUPUESTO");
        jPanel14.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 300, 50));
        jPanel14.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, -30, -1, -1));

        jLabel33.setText("A budget helps users allocate their income to different categories for effective financial management and goal achievement.");

        BudgetExpenseCategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--", " " }));

        removeBudgetComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--" }));

        BudgetAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BudgetAmountActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setText("Allocate Budget");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel35.setText("Expense Category");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel36.setText("Add New Category");

        addBudgetExpenseCategoryButton.setBackground(new java.awt.Color(55, 98, 217));
        addBudgetExpenseCategoryButton.setForeground(new java.awt.Color(255, 255, 255));
        addBudgetExpenseCategoryButton.setText("Add");
        addBudgetExpenseCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBudgetExpenseCategoryButtonActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel37.setText("Remove Budget");

        removeBudgetButton.setBackground(new java.awt.Color(55, 98, 217));
        removeBudgetButton.setForeground(new java.awt.Color(255, 255, 255));
        removeBudgetButton.setText("Remove");
        removeBudgetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBudgetButtonActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel38.setText("Amount");

        addBudget.setBackground(new java.awt.Color(55, 98, 217));
        addBudget.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addBudget.setForeground(new java.awt.Color(255, 255, 255));
        addBudget.setText("Allocate Budget");
        addBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBudgetActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel39.setText("Target Amount");

        jLabel40.setText("(amount which you are targeting to save in this month)");

        addTargetAmountButton.setBackground(new java.awt.Color(55, 98, 217));
        addTargetAmountButton.setForeground(new java.awt.Color(255, 255, 255));
        addTargetAmountButton.setText("Add");
        addTargetAmountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTargetAmountButtonActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel42.setText("Budget's");

        budgetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Expense Category", "Amount"
            }
        ));
        jScrollPane7.setViewportView(budgetTable);

        javax.swing.GroupLayout Budget_tabLayout = new javax.swing.GroupLayout(Budget_tab);
        Budget_tab.setLayout(Budget_tabLayout);
        Budget_tabLayout.setHorizontalGroup(
            Budget_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Budget_tabLayout.createSequentialGroup()
                .addGroup(Budget_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Budget_tabLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel33))
                    .addGroup(Budget_tabLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel34))
                    .addGroup(Budget_tabLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel35)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(jLabel38))
                    .addGroup(Budget_tabLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel39)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel40))
                    .addGroup(Budget_tabLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(targetAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(addTargetAmountButton))
                    .addGroup(Budget_tabLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel37))
                    .addGroup(Budget_tabLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(removeBudgetComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(removeBudgetButton))
                    .addGroup(Budget_tabLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel42))
                    .addGroup(Budget_tabLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Budget_tabLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(BudgetExpenseCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(BudgetExpenseCategoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(addBudgetExpenseCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(BudgetAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addBudget)))
                .addContainerGap(670, Short.MAX_VALUE))
        );
        Budget_tabLayout.setVerticalGroup(
            Budget_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Budget_tabLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel33)
                .addGap(14, 14, 14)
                .addComponent(jLabel34)
                .addGap(10, 10, 10)
                .addGroup(Budget_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Budget_tabLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel38)))
                .addGap(10, 10, 10)
                .addGroup(Budget_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BudgetExpenseCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BudgetExpenseCategoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBudgetExpenseCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Budget_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BudgetAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(Budget_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(Budget_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(targetAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTargetAmountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel37)
                .addGap(10, 10, 10)
                .addGroup(Budget_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(removeBudgetComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeBudgetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel42)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PRESUPUESTOS_TAB_SCROLLPANE.setViewportView(Budget_tab);

        INTERFAZ_INTERACTIVA_PANE.addTab("PRESUPUESTO", PRESUPUESTOS_TAB_SCROLLPANE);

        Expense.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel13.setText("AÑADIR GASTOS");
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 50));
        jPanel10.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, -30, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Account");

        expenseAccountName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--" }));
        expenseAccountName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expenseAccountNameActionPerformed(evt);
            }
        });

        jPanel11.setBackground(new java.awt.Color(241, 241, 237));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Add Category");
        jPanel11.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 110, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Amount");
        jPanel11.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 100, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Remark");
        jPanel11.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 80, 30));

        jPanel13.setBackground(new java.awt.Color(241, 241, 237));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("Category");
        jPanel13.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 110, 30));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("Amount");
        jPanel13.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 100, 30));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setText("Remark");
        jPanel13.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 80, 30));

        jPanel11.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 860, 30));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setText("Category");
        jPanel11.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 110, 30));

        expenseCategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--" }));
        expenseCategoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expenseCategoryComboBoxActionPerformed(evt);
            }
        });

        expenseCategoryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expenseCategoryTextFieldActionPerformed(evt);
            }
        });

        expenseRemark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expenseRemarkActionPerformed(evt);
            }
        });

        ExpenseAddButton.setBackground(new java.awt.Color(55, 98, 217));
        ExpenseAddButton.setForeground(new java.awt.Color(255, 255, 255));
        ExpenseAddButton.setText("Add");
        ExpenseAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpenseAddButtonActionPerformed(evt);
            }
        });

        ExpenseResetButton.setBackground(new java.awt.Color(55, 98, 217));
        ExpenseResetButton.setForeground(new java.awt.Color(255, 255, 255));
        ExpenseResetButton.setText("Reset");
        ExpenseResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpenseResetButtonActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Date");

        expenseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Account", "Category", "Amount", "Date", "Remark"
            }
        ));
        jScrollPane4.setViewportView(expenseTable);

        addExpenseCategory.setBackground(new java.awt.Color(55, 98, 217));
        addExpenseCategory.setForeground(new java.awt.Color(255, 255, 255));
        addExpenseCategory.setText("Add");
        addExpenseCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExpenseCategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Expense_TabLayout = new javax.swing.GroupLayout(Expense_Tab);
        Expense_Tab.setLayout(Expense_TabLayout);
        Expense_TabLayout.setHorizontalGroup(
            Expense_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(Expense_TabLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(Expense_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Expense_TabLayout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(360, 360, 360)
                        .addComponent(jLabel15))
                    .addGroup(Expense_TabLayout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(expenseAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Expense_TabLayout.createSequentialGroup()
                        .addComponent(expenseCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(expenseCategoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(addExpenseCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(expenseAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(expenseRemark, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Expense_TabLayout.createSequentialGroup()
                        .addComponent(ExpenseAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(ExpenseResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        Expense_TabLayout.setVerticalGroup(
            Expense_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Expense_TabLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(Expense_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel15))
                .addGap(10, 10, 10)
                .addComponent(expenseAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(Expense_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(expenseCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expenseCategoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addExpenseCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expenseAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expenseRemark, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(Expense_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExpenseAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExpenseResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Expense.add(Expense_Tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1530, 710));

        GASTOS_TAB_SCROLLPANE.setViewportView(Expense);

        INTERFAZ_INTERACTIVA_PANE.addTab("GASTOS", GASTOS_TAB_SCROLLPANE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barra_superior, javax.swing.GroupLayout.DEFAULT_SIZE, 1532, Short.MAX_VALUE)
            .addComponent(INTERFAZ_INTERACTIVA_PANE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(barra_superior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INTERFAZ_INTERACTIVA_PANE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BUTTON_CUENTASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_CUENTASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BUTTON_CUENTASActionPerformed

    private void BUTTON_CERRAR_SESIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_CERRAR_SESIONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BUTTON_CERRAR_SESIONActionPerformed

    private void balanceLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balanceLabelActionPerformed

    private void GENERAR_GRAFICO_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GENERAR_GRAFICO_BUTTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GENERAR_GRAFICO_BUTTONActionPerformed

    private void deleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteAccountActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void createAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createAccountActionPerformed

    private void incomeSourceComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomeSourceComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_incomeSourceComboBoxActionPerformed

    private void incomeAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomeAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_incomeAmountActionPerformed

    private void incomeAccountNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomeAccountNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_incomeAccountNameActionPerformed

    private void addIncomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIncomeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addIncomeButtonActionPerformed

    private void resetIncomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetIncomeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetIncomeButtonActionPerformed

    private void addIncomeSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIncomeSourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addIncomeSourceActionPerformed

    private void expenseAccountNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expenseAccountNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expenseAccountNameActionPerformed

    private void expenseCategoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expenseCategoryComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expenseCategoryComboBoxActionPerformed

    private void expenseCategoryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expenseCategoryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expenseCategoryTextFieldActionPerformed

    private void expenseRemarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expenseRemarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expenseRemarkActionPerformed

    private void ExpenseAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpenseAddButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpenseAddButtonActionPerformed

    private void ExpenseResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpenseResetButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpenseResetButtonActionPerformed

    private void addExpenseCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExpenseCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addExpenseCategoryActionPerformed

    private void BudgetAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BudgetAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BudgetAmountActionPerformed

    private void addBudgetExpenseCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBudgetExpenseCategoryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBudgetExpenseCategoryButtonActionPerformed

    private void removeBudgetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBudgetButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeBudgetButtonActionPerformed

    private void addBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBudgetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBudgetActionPerformed

    private void addTargetAmountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTargetAmountButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTargetAmountButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMacLightLaf.setup(); // inicializacion de flatlaf e importacion del tema a usar

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AHORRO_MENSUAL_TXT;
    private javax.swing.JProgressBar BARRA_DE_PROGRESO;
    private javax.swing.JToggleButton BUTTON_AYUDA;
    private javax.swing.JButton BUTTON_CERRAR_SESION;
    private javax.swing.JToggleButton BUTTON_CUENTAS;
    private javax.swing.JToggleButton BUTTON_GASTOS;
    private javax.swing.JToggleButton BUTTON_INGRESOS;
    private javax.swing.JToggleButton BUTTON_INICIO;
    private javax.swing.JToggleButton BUTTON_PRESUPUESTOS;
    private javax.swing.JTextField BudgetAmount;
    private javax.swing.JComboBox<String> BudgetExpenseCategoryComboBox;
    private javax.swing.JTextField BudgetExpenseCategoryTextField;
    private javax.swing.JPanel Budget_tab;
    private javax.swing.JPanel CUENTAS_TAB;
    private javax.swing.JPanel Expense;
    private javax.swing.JButton ExpenseAddButton;
    private javax.swing.JButton ExpenseResetButton;
    private javax.swing.JPanel Expense_Tab;
    private javax.swing.JPanel GASTOS_DEL_MES_PANEL;
    private javax.swing.JScrollPane GASTOS_TAB_SCROLLPANE;
    private javax.swing.JButton GENERAR_GRAFICO_BUTTON;
    private javax.swing.JPanel INGRESOS_DEL_MES_PANEL;
    private javax.swing.JScrollPane INGRESOS_TAB_SCROLLPANE;
    private javax.swing.JPanel INICIO_PANEL;
    private javax.swing.JScrollPane INICIO_TAB_SCROLLPANE;
    private javax.swing.JTabbedPane INTERFAZ_INTERACTIVA_PANE;
    private javax.swing.JPanel Income_tab;
    private javax.swing.JLabel MONTO_AHORRADO;
    private javax.swing.JScrollPane PRESUPUESTOS_TAB_SCROLLPANE;
    private javax.swing.JPanel RESPONSABILIDAD_PANEL;
    private javax.swing.JPanel SALDO_ACTUAL_PANEL;
    private javax.swing.JScrollPane TABLA_DE_TRANSACCIONES;
    private javax.swing.JLabel TRANSACCIONES_TEXT;
    private javax.swing.JPanel VISUALIZACION_AHORRO;
    private javax.swing.JTable accountTable;
    private javax.swing.JButton addBudget;
    private javax.swing.JButton addBudgetExpenseCategoryButton;
    private javax.swing.JButton addExpenseCategory;
    private javax.swing.JButton addIncomeButton;
    private javax.swing.JButton addIncomeSource;
    private javax.swing.JButton addTargetAmountButton;
    private javax.swing.JTextField balanceLabel;
    private javax.swing.JPanel barra_superior;
    private javax.swing.JTable budgetTable;
    private javax.swing.JButton createAccount;
    private javax.swing.JButton deleteAccount;
    private javax.swing.JComboBox<String> expenseAccountName;
    private javax.swing.JTextField expenseAmount;
    private javax.swing.JComboBox<String> expenseCategoryComboBox;
    private javax.swing.JTextField expenseCategoryTextField;
    private javax.swing.JTextField expenseLabel;
    private javax.swing.JTextField expenseRemark;
    private javax.swing.JTable expenseTable;
    private javax.swing.JComboBox<String> incomeAccountName;
    private javax.swing.JTextField incomeAmount;
    private javax.swing.JTextField incomeLabel;
    private javax.swing.JComboBox<String> incomeSourceComboBox;
    private javax.swing.JTextField incomeSourceTextField;
    private javax.swing.JTable incomeTable;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField liabilitiesLabel;
    private javax.swing.JButton removeBudgetButton;
    private javax.swing.JComboBox<String> removeBudgetComboBox;
    private javax.swing.JButton resetIncomeButton;
    private javax.swing.JTextField targetAmountTextField;
    private javax.swing.JTable transactionTable;
    // End of variables declaration//GEN-END:variables
}
